language: ruby
bundler_args: --binstubs=./bundler_stubs --without development
before_install: gem update bundler
env:
  - DB=sqlite
rvm:
  - 2.0.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
