language: ruby
bundler_args: --without development
services:
  - mongodb
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - ree
  - jruby-19mode
  - jruby-head
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: ree
    - rvm: jruby-19mode
    - rvm: jruby-head
